### ISSUE TITLE
java.lang.NoSuchFieldError: No static field MD_Dark of type I in class Lcom/github/javiersantos/materialstyleddialogs/R$styl

### ISSUE THREAD

**Issue by mengtrue** [javiersantos/MaterialStyledDialogs#70]
- [√] I have verified there are no duplicate active or recent bugs, questions, or requests.
- [√] I have verified that I am using the latest version of MaterialStyledDialogs.
- [√] I have given my issue a non-generic title.
- [√] I have read over the [README](https://github.com/javiersantos/MaterialStyledDialogs/blob/master/README.md) and [Wiki](https://github.com/javiersantos/MaterialStyledDialogs/wiki) (before asking questions on how to do something).

###### Details
 - MaterialStyledDialogs version: `2.1`
 - Device OS version: `8.0`
 - Device Manufacturer: `OnePlus`
 - Device Name: `OnePlus A3000`

###### Reproduction Steps

1.add this library in my app project
2.add code for MaterialStyledDialog
3.show the dialog

###### Expected Result
APP crash
the log is 
07-25 10:28:06.238 E 16352    16352    AndroidRuntime:                                                    java.lang.NoSuchFieldError: No static field MD_Dark of type I in class Lcom/github/javiersantos/materialstyleddialogs/R$style; or its superclasses (declaration of com.github.javiersantos.materialstyleddialogs.R$style appears in /data/app/com.gtk.smartmanagement-WV22AVku43YBXFAZ3rCTbQ==/split_lib_slice_2_apk.apk) 
07-25 10:28:06.238 E 16352    16352    AndroidRuntime:                                                    	at com.github.javiersantos.materialstyleddialogs.MaterialStyledDialog.<init>(MaterialStyledDialog.java:37) 
07-25 10:28:06.238 E 16352    16352    AndroidRuntime:                                                    	at com.github.javiersantos.materialstyleddialogs.MaterialStyledDialog$Builder.build(MaterialStyledDialog.java:457) 
07-25 10:28:06.238 E 16352    16352    AndroidRuntime:                                                    	at com.github.javiersantos.materialstyleddialogs.MaterialStyledDialog$Builder.show(MaterialStyledDialog.java:462) 

###### Actual Result
The dialog shoule be showed normal.

**Comment by mengtrue** [comment]
After check source code, add 
`implementation 'com.afollestad.material-dialogs:core:0.9.6.0'`
it can work.
Maybe you can add this on README
